# Generated by Django 5.1.1 on 2024-09-20 18:07

import app.models
import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAgencia', models.CharField(max_length=100, verbose_name='Nome da Agência')),
                ('numeroAgencia', models.CharField(default='0000000000', editable=False, max_length=10, unique=True)),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço da Agência')),
            ],
            options={
                'verbose_name': 'Agencia',
                'verbose_name_plural': 'Agencias',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('CPF', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('endereco', models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('senha', models.CharField(max_length=255, verbose_name='Senha')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True)),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=app.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('numeroConta', models.CharField(default=0, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('tipoConta', models.CharField(choices=[('corrente', 'Corrente'), ('poupanca', 'Poupança')], max_length=10)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('limiteCredito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldoDisponivel', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('dataAbertura', models.DateField(auto_now_add=True)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.agencia')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroCartao', models.BigIntegerField(blank=True, unique=True)),
                ('bandeira', models.CharField(choices=[('visa', 'Visa'), ('elo', 'Elo'), ('mastercard', 'MasterCard')], default='visa', max_length=20)),
                ('cvv', models.IntegerField(blank=True)),
                ('dataExpiracao', models.DateField(blank=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.conta')),
            ],
            options={
                'verbose_name': 'Cartão',
                'verbose_name_plural': 'Cartões',
            },
        ),
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=255)),
                ('dataHora', models.DateTimeField(auto_now_add=True)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cliente')),
                ('conta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.conta')),
            ],
            options={
                'verbose_name': 'Extrato',
                'verbose_name_plural': 'Extratos',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoNotificacao', models.CharField(choices=[('transacao', 'Transação'), ('seguranca', 'Segurança'), ('informativo', 'Informativo')], max_length=15)),
                ('mensagem', models.TextField()),
                ('dataEnvio', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoTransacao', models.CharField(choices=[('deposito', 'Depósito'), ('saque', 'Saque'), ('transferencia', 'Transferência'), ('pagamento', 'Pagamento')], max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dataHora', models.DateTimeField(auto_now_add=True)),
                ('dataAgendamento', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='concluida', max_length=10)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='app.conta')),
                ('contaDestino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias', to='app.conta')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
            },
        ),
    ]
