# Generated by Django 5.1.1 on 2024-10-08 16:17

import app.models
import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('nomeagencia', models.CharField(max_length=100, verbose_name='Nome da Agência')),
                ('numeroagencia', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Agência',
                'verbose_name_plural': 'Agências',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('CPF', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail')),
                ('telefone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone')),
                ('senha', models.CharField(max_length=255, verbose_name='Senha')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True)),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=app.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('rua', models.CharField(max_length=100, verbose_name='Rua')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('estado', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='Estado')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(max_length=50, verbose_name='Complemento')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('numeroConta', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Número da Conta')),
                ('dataAbertura', models.DateField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.agencia')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroCartao', models.BigIntegerField(blank=True, editable=False, unique=True, verbose_name='Numero do Cartão')),
                ('bandeira', models.CharField(choices=[('visa', 'Visa'), ('elo', 'Elo'), ('mastercard', 'MasterCard')], default='visa', max_length=20, verbose_name='Bandeira')),
                ('dataExpiracao', models.DateField(blank=True, editable=False, verbose_name='Data de Expiração')),
                ('cvv', models.IntegerField(blank=True, editable=False, verbose_name='CVV')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.conta')),
            ],
            options={
                'verbose_name': 'Cartão',
                'verbose_name_plural': 'Cartões',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.endereco'),
        ),
        migrations.AddField(
            model_name='agencia',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.endereco'),
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('dataHora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='app.conta')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('numeroTransacao', models.AutoField(primary_key=True, serialize=False, verbose_name='Número da Transação')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('tipoTransacao', models.CharField(choices=[('deposito', 'Depósito'), ('saque', 'Saque'), ('transferencia', 'Transferência')], max_length=50, verbose_name='Tipo de Transação')),
                ('status', models.CharField(default='pendente', editable=False, max_length=20, verbose_name='Status')),
                ('dataHora', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data e Hora da Transação')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='app.conta')),
                ('contaDestino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_destino', to='app.conta')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
            },
        ),
    ]
