# Generated by Django 5.1.1 on 2024-11-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Sobrenome'),
        ),
    ]
