# Generated by Django 5.1.1 on 2024-10-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='dataEnvio',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de envio'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='dataHora',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data e Hora'),
        ),
    ]
