# Generated by Django 5.1.1 on 2024-10-03 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacao',
        ),
    ]
