# Generated by Django 5.1.1 on 2024-11-27 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cliente_email_alter_cliente_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cliente',
            managers=[
            ],
        ),
    ]
