# Generated by Django 5.1.1 on 2024-10-03 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_notificacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencia',
            options={'verbose_name': 'Agência', 'verbose_name_plural': 'Agências'},
        ),
    ]
