# Generated by Django 5.1.1 on 2024-10-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_endereco_options_remove_cliente_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(max_length=50, null=True, verbose_name='Complemento'),
        ),
    ]
