# Generated by Django 5.1.1 on 2024-10-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_notificacao_conta_notificacao_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='status',
            field=models.CharField(default='pendente', max_length=50),
        ),
    ]
