# Generated by Django 5.1.1 on 2024-10-03 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_agencia_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='contaDestino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_destino', to='app.conta'),
        ),
    ]
