# Generated by Django 5.1.1 on 2024-10-03 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_transacao_cliente_alter_transacao_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='transacao',
            name='contaDestino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_destino', to='app.conta'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='dataHora',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Transação'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='numeroTransacao',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Número da Transação'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='status',
            field=models.CharField(default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipoTransacao',
            field=models.CharField(choices=[('deposito', 'Depósito'), ('saque', 'Saque'), ('transferencia', 'Transferência')], max_length=50, verbose_name='Tipo de Transação'),
        ),
    ]
