# Generated by Django 5.1.1 on 2024-10-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_cartao_cliente_alter_conta_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencia',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AlterField(
            model_name='agencia',
            name='numeroagencia',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='CPF',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='status',
            field=models.CharField(choices=[('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='Pendente', editable=False, max_length=10, verbose_name='Status'),
        ),
    ]
