# Generated by Django 5.1.1 on 2024-10-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_transacao_cliente_remove_transacao_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='dataHora',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data e Hora da Transação'),
        ),
    ]
