# Generated by Django 5.1.1 on 2024-10-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_agencia_id_remove_cliente_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
    ]
