# Generated by Django 5.1.1 on 2024-11-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cartao_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='bandeira',
            field=models.CharField(choices=[('VISA', 'Visa'), ('ELO', 'Elo'), ('MASTERCARD', 'MasterCard')], default='visa', max_length=20, verbose_name='Bandeira'),
        ),
    ]
