# Generated by Django 5.1.1 on 2024-10-07 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_transacao_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('dataHora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='app.conta')),
            ],
        ),
    ]
