# Generated by Django 5.1.1 on 2024-10-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_endereco_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='numeroagencia',
            field=models.IntegerField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
