# Generated by Django 5.1.1 on 2024-11-19 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cliente_is_active_cliente_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='senha',
        ),
    ]
