# Generated by Django 5.1.1 on 2024-11-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_cliente_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='senha',
            field=models.CharField(default=0, max_length=25, verbose_name='Senha'),
            preserve_default=False,
        ),
    ]
