# Generated by Django 5.1.1 on 2024-11-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_cliente_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='senha',
        ),
    ]
