# Generated by Django 5.1.1 on 2024-10-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_conta_numeroconta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='numeroConta',
            field=models.IntegerField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Número da Conta'),
        ),
    ]
